exclude : '.*(\.(asset|meta|mat|unity|prefab))'

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
        files : .*(\.py|\.cs)
        #exclude : '(isort\.cfg|*.(\.svg))' # some weird conflict that is never resolved...
    -   id: trailing-whitespace

- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort
      name: isort (python)

-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        name: black
        language_version: python3.8
        types: [python]
        stages: [commit]

- repo: local
  hooks:
    - id: lint
      name: lint
      entry: python test/lint.py
      language: system
      pass_filenames: false
      log_file: logs/lint.log
