site_name: World of Bugs
theme: 
    name: readthedocs
    navigation_depth: 10
plugins:
    - search
    - awesome-pages:
        collapse_single_pages: true
    # - autolinks
    # - section-index
    # - literate-nav