site_name: World of Bugs
theme: 
    name: material
    features:
    - navigation.indexes
    - navigation.sections
    #- navigation.expand
    #- navigation.tabs
    #- toc.integrate
  
plugins:
    #- search
    - awesome-pages:
    # - autolinks
    # - section-index
    # - literate-nav